name: Checkmarx AST Scan
on:
  push:
    branches:
      - main
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkmarx AST CLI Action
        uses: checkmarx/ast-github-action@main #Github Action version
        with:
          project_name: New_lab
          cx_tenant: ps_prayash_mishra
          base_uri: https://ind.ast.checkmarx.net/
          cx_client_id: ${{ secrets.firstpipeline }}
          cx_client_secret: ${{ secrets.O3h5ZLJy5HLVw5XVl5FrE2bQ78cvdGjf }}
